=== ifolks-open-source-community/ifolks-generator/generator-model/src/main/resources/skeleton-metadata-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="http://generator.ifolks.org/schema/model/metadata" xmlns:metadata="http://generator.ifolks.org/schema/model/metadata" xmlns:tns="http://generator.ifolks.org/schema/model/metadata" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="project" type="tns:project"/>

  <xs:complexType name="accessRoles">
    <xs:sequence/>
    <xs:attribute name="readRole" type="xs:string"/>
    <xs:attribute name="createRole" type="xs:string"/>
    <xs:attribute name="saveRole" type="xs:string"/>
    <xs:attribute name="updateRole" type="xs:string"/>
    <xs:attribute name="deleteRole" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="column">
    <xs:sequence>
      <xs:element name="annotations" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="annotation" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="dataType" type="tns:dataType"/>
    <xs:attribute name="nullable" type="xs:boolean"/>
    <xs:attribute name="unique" type="xs:boolean"/>
    <xs:attribute name="referenceTableName" type="xs:string"/>
    <xs:attribute name="referenceTableRelation" type="tns:relationType"/>
    <xs:attribute name="editable" type="xs:boolean"/>
    <xs:attribute name="filterable" type="xs:boolean"/>
    <xs:attribute name="textFilterType" type="tns:textFilterType"/>
    <xs:attribute name="visibility" type="tns:visibility"/>
    <xs:attribute name="rendering" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="index">
    <xs:sequence>
      <xs:element name="fields" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="package">
    <xs:sequence>
      <xs:element name="tables" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="table" type="tns:table" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="packages" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="package" type="tns:package" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="table">
    <xs:sequence>
      <xs:element name="selectionBehavior" type="tns:selectionBehavior" minOccurs="0"/>
      <xs:element name="accessRoles" type="tns:accessRoles" minOccurs="0"/>
      <xs:element name="interfaces" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="interface" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="annotations" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="annotation" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="columns" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="column" type="tns:column" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="uniqueConstraints" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="uniqueConstraint" type="tns:uniqueConstraint" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="indexes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="index" type="tns:index" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="idType" type="tns:dataType"/>
    <xs:attribute name="idGeneratorType" type="tns:idGeneratorType"/>
    <xs:attribute name="cardinality" type="xs:int" use="required"/>
    <xs:attribute name="listRendering" type="xs:string"/>
    <xs:attribute name="detailRendering" type="xs:string"/>
    <xs:attribute name="createEnabled" type="xs:boolean"/>
    <xs:attribute name="updateEnabled" type="xs:boolean"/>
    <xs:attribute name="deleteEnabled" type="xs:boolean"/>
    <xs:attribute name="detailMode" type="tns:detailMode"/>
  </xs:complexType>

  <xs:complexType name="selectionBehavior">
    <xs:sequence/>
    <xs:attribute name="selectionMode" type="tns:selectionMode" use="required"/>
    <xs:attribute name="labelColumn" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="uniqueConstraint">
    <xs:sequence>
      <xs:element name="fields" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="project">
    <xs:sequence>
      <xs:element name="domainName" type="xs:string"/>
      <xs:element name="projectName" type="xs:string"/>
      <xs:element name="skeleton" type="xs:string"/>
      <xs:element name="databaseEngine" type="xs:string"/>
      <xs:element name="tablesTableSpace" type="xs:string" minOccurs="0"/>
      <xs:element name="indexesTableSpace" type="xs:string" minOccurs="0"/>
      <xs:element name="packages" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="package" type="tns:package" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="dataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TEXT"/>
      <xs:enumeration value="STRING"/>
      <xs:enumeration value="SHORT"/>
      <xs:enumeration value="INTEGER"/>
      <xs:enumeration value="LONG"/>
      <xs:enumeration value="DOUBLE"/>
      <xs:enumeration value="BIG_DECIMAL"/>
      <xs:enumeration value="DATE"/>
      <xs:enumeration value="DATETIME"/>
      <xs:enumeration value="BOOLEAN"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="relationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MANY_TO_ONE"/>
      <xs:enumeration value="MANY_TO_ONE_COMPONENT"/>
      <xs:enumeration value="EMBEDDED"/>
      <xs:enumeration value="ONE_TO_ONE"/>
      <xs:enumeration value="ONE_TO_ONE_COMPONENT"/>
      <xs:enumeration value="PROPERTY"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="textFilterType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STARTS_WITH"/>
      <xs:enumeration value="CONTAINS"/>
      <xs:enumeration value="CONTAINS_IGNORE_ACCENTS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="visibility">
    <xs:restriction base="xs:string">
      <xs:enumeration value="VISIBLE"/>
      <xs:enumeration value="NOT_LIST"/>
      <xs:enumeration value="NOT_VISIBLE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="detailMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MODAL"/>
      <xs:enumeration value="PAGE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idGeneratorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE"/>
      <xs:enumeration value="SEQUENCE"/>
      <xs:enumeration value="UUID"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="selectionMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DROPDOWN_OPTIONS"/>
      <xs:enumeration value="AUTO_COMPLETE"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="persistenceMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TXT"/>
      <xs:enumeration value="CSV"/>
      <xs:enumeration value="XML"/>
      <xs:enumeration value="CMD"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ifolks-open-source-community/ifolks-generator/generator-tests/src/test/resources/projects/success/1/data-model/skeleton.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata:project xmlns:metadata="http://generator.ifolks.org/schema/model/metadata"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://generator.ifolks.org/schema/model/metadata skeleton-metadata-1.0.xsd">
	<domainName>org.ifolks</domainName>
	<projectName>demo</projectName>
	<skeleton>SPRING_HIBERNATE_PRIMEFACES</skeleton>
	<databaseEngine>POSTGRESQL</databaseEngine>

	<packages>
		<package name="REFERENCE">
			<packages>
				<package name="LOCALIZATION">
					<tables>
						<table name="COUNTRY" cardinality="1" listRendering="Countries"
							detailRendering="Country details" createEnabled="true"
							updateEnabled="true" deleteEnabled="true">
							<selectionBehavior selectionMode="DROPDOWN_OPTIONS" />
							<columns>
								<column name="CODE" dataType="STRING" nullable="false"
									editable="true" rendering="ISO Code">
								</column>
								<column name="LABEL" dataType="STRING" nullable="false"
									editable="true" rendering="Label">
								</column>
							</columns>
						</table>
						<table name="REGION" cardinality="2" listRendering="Regions/States/Provinces"
							detailRendering="Region details" createEnabled="true"
							updateEnabled="true" deleteEnabled="true">
							<columns>
								<column name="COUNTRY_ID" dataType="LONG"
									referenceTableName="COUNTRY" referenceTableRelation="MANY_TO_ONE"
									nullable="false" editable="true" rendering="Country">
								</column>
								<column name="CODE" dataType="STRING" nullable="false"
									editable="true" rendering="Code">
								</column>
								<column name="LABEL" dataType="STRING" nullable="false"
									editable="true" rendering="Label">
								</column>
							</columns>
						</table>
						<table name="CITY" cardinality="2" listRendering="Cities"
							detailRendering="City details" createEnabled="true"
							updateEnabled="true" deleteEnabled="true">
							<columns>
								<column name="REGION_ID" dataType="LONG"
									referenceTableName="REGION" referenceTableRelation="MANY_TO_ONE"
									nullable="false" editable="true" rendering="Region">
								</column>
								<column name="CODE" dataType="STRING" nullable="false"
									editable="true" rendering="Code">
								</column>
								<column name="LABEL" dataType="STRING" nullable="false"
									editable="true" rendering="Label">
								</column>
							</columns>
						</table>
					</tables>
				</package>
				<package name="TIME">
					<tables>
						<table name="CALENDAR" cardinality="1" listRendering="Calendars"
							detailRendering="Calendar details" createEnabled="true"
							updateEnabled="true" deleteEnabled="true">
							<selectionBehavior selectionMode="DROPDOWN_OPTIONS" />
							<columns>
								<column name="CODE" dataType="STRING" nullable="false"
									editable="true" rendering="Code">
								</column>
								<column name="LABEL" dataType="STRING" nullable="false"
									editable="true" rendering="Label">
								</column>
							</columns>
						</table>
						<table name="CALENDAR_DAY_OFF" cardinality="2"
							listRendering="Days off" detailRendering="Day off" createEnabled="true"
							updateEnabled="true" deleteEnabled="true">
							<columns>
								<column name="CALENDAR_ID" dataType="LONG" nullable="false"
									referenceTableName="CALENDAR" referenceTableRelation="MANY_TO_ONE_COMPONENT"
									editable="true" rendering="User">
								</column>
								<column name="DAY_OFF_DATE" dataType="DATETIME" nullable="false"
									editable="true" rendering="Date">
								</column>
								<column name="DAY_OFF_LABEL" dataType="STRING" nullable="true"
									editable="true" rendering="Label">
								</column>
							</columns>
						</table>
					</tables>
				</package>
			</packages>
		</package>
		<package name="ORGANIZATIONS">
			<tables>
				<table cardinality="1" name="ORGANIZATION" listRendering="Organizations"
					detailRendering="Organization">
					<selectionBehavior selectionMode="AUTO_COMPLETE" />
					<columns>
						<column name="CODE" dataType="STRING" nullable="false"
							editable="true" rendering="Code">
						</column>
						<column name="ORGANIZATION_DESCRIPTION_ID" dataType="LONG"
							nullable="false" editable="true" rendering="Code"
							referenceTableName="ORGANIZATION_DESCRIPTION"
							referenceTableRelation="EMBEDDED">
						</column>
					</columns>
				</table>
				<table cardinality="0" name="ORGANIZATION_DESCRIPTION">
					<columns>
						<column name="DESCRIPTION" dataType="TEXT" nullable="true"
							editable="true" rendering="Description">
						</column>
					</columns>
				</table>
				<table cardinality="1" name="ORGANIZATION_CERTIFICATION"
					listRendering="Certifications" detailRendering="Certification">
					<columns>
						<column name="ORGANIZATION_ID" dataType="LONG" nullable="true"
							editable="true" rendering="Description" referenceTableName="ORGANIZATION"
							referenceTableRelation="ONE_TO_ONE_COMPONENT">
						</column>
						<column name="CERTIFIED" dataType="BOOLEAN" nullable="false"
							editable="true" rendering="Certified">
						</column>
					</columns>
				</table>
			</tables>
		</package>
		<package name="DUMMY">
			<tables>
				<table name="FOOL" cardinality="1" listRendering="Fools"
					detailRendering="Fool details" createEnabled="true" updateEnabled="true"
					deleteEnabled="true">
					<selectionBehavior selectionMode="AUTO_COMPLETE" />
					<columns>
						<column name="CODE" dataType="STRING" nullable="false"
							editable="true" rendering="Code">
						</column>
						<column name="DESCRIPTION" dataType="TEXT" nullable="true"
							editable="true" rendering="Description">
						</column>
						<column name="LONG_FIELD" dataType="LONG" nullable="true"
							editable="true" rendering="Long">
						</column>
						<column name="BOOLEAN_FIELD" dataType="BOOLEAN" nullable="true"
							editable="true" rendering="Boolean">
						</column>
						<column name="DOUBLE_FIELD" dataType="DOUBLE" nullable="true"
							editable="true" rendering="Double">
						</column>
						<column name="DECIMAL_FIELD" dataType="BIG_DECIMAL"
							nullable="true" editable="true" rendering="Decimal">
						</column>
						<column name="DATE_FIELD" dataType="DATE" nullable="true"
							editable="true" rendering="Date">
						</column>
						<column name="DATETIME_FIELD" dataType="DATETIME" nullable="true"
							editable="true" rendering="Date and time">
						</column>
					</columns>
				</table>
				<table name="STUPID" cardinality="1" listRendering="Stupids"
					detailRendering="Stupid details" createEnabled="true"
					updateEnabled="true" deleteEnabled="true">
					<columns>
						<column name="CODE" dataType="STRING" nullable="false"
							editable="true" rendering="Code">
						</column>
						<column name="FOOL_ID" dataType="LONG" nullable="false"
							referenceTableName="FOOL" editable="true" rendering="Fool">
						</column>
					</columns>
				</table>
			</tables>
		</package>
	</packages>
</metadata:project>
